# See https://pre-commit.com/ for usage and config
default_language_version:
    python: python3.10

files: ^src/.*\.py$

repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: pdm run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pdm run black
    types: [python]

  - id: pylint
    name: pylint
    stages: [commit]
    language: system
    entry: pdm run pylint
    types: [python]

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: pdm run mypy src
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pdm run test
    types: [python]
    pass_filenames: false
