# See https://pre-commit.com/ for usage and config
default_language_version:
    python: python3.12

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: pytest
      name: pytest
      stages: [pre-commit]
      language: system
      entry: uv run pytest
      types: [python]
      pass_filenames: false
