# See https://pre-commit.com/ for usage and config
default_language_version:
    python: python3.10

files: ^src/.*\.py$

repos:
- repo: local
  hooks:

  - id: black
    name: black
    stages: [pre-commit]
    language: system
    entry: pdm run black
    types: [python]

  - id: ruff
    name: ruff
    stages: [pre-commit]
    language: system
    entry: pdm run ruff check --fix --respect-gitignore
    types: [python]

  - id: mypy
    name: mypy
    stages: [pre-commit]
    language: system
    entry: pdm run mypy src
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    stages: [pre-commit]
    language: system
    entry: pdm run test
    types: [python]
    pass_filenames: false
